name: CI for project_service
on:
  pull:
    branches:
      - centaur-master-bc5
  pull_request:
    branches:
      - centaur-master-bc5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run tests
        run: ./gradlew test --no-daemon