spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER_PORT=9009
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false

calculations_messages_processing:
  enabled: false

services:
  user-service:
    name: User Service
    host: http://localhost
    port: 8080