spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8082

logging:
  level:
    root: info

calculations_messages_processing:
  enabled: true

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: projectbucket
    isMocked: false
    region: us-east-1
  payment-service:
    host: http://localhost
    port: 9080
  user-service:
    host: http://localhost
    port: 8080

entity:
    project:
        default-storage-size: 2

google:
  service-account:
    key-file-path: kelpie10google.json
  api:
    url: https://www.googleapis.com/
  calendar:
    id: 948a850ea2013122e19246b99a8b9c2caeed1bac182d7928d4bd158ec1f06182@group.calendar.google.com