spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  config:
    import: optional:file:.env

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: project-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: faang.school.projectservice.dto

server:
  port: 8082

logging:
  level:
    root: info

calculations_messages_processing:
  enabled: true

project-service:
  api-version: /api/v1
  jira:
    url: https://shakhzodkamolov.atlassian.net/rest/api/2
    username: ${JIRA_USERNAME}
    token: ${JIRA_TOKEN}
  redis:
    port: 6379
    host: localhost
    channel:
      calculations_channel: calculations_channel
  kafka:
    team-topic: team_topic


services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: projectbucket
    isMocked: false
  payment-service:
    host: http://localhost
    port: 9080
  user-service:
    host: http://localhost
    port: 8080